tools/importer/import.js

Fix for subtitle, cleanup tags and not remove hero image
Fix #2 
Test URLs:
- After: https://issue-2-import-script--channelco-iot--hlxsites.hlx.page/

finessing import to fix subtitle, tags and img

---

.stylelintrc.json
package-lock.json
package.json
styles/styles.css

Fix #1 <gh-issue-id>
Test URLs:
- Before: https://main--channelco-iot--hlxsites.hlx.page/verticals/healthcare/3d-printing-is-new-antidote-for-healthcare-costs
- After: https://issue-1-update-global-styles--channelco-iot--hlxsites.hlx.page/verticals/healthcare/3d-printing-is-new-antidote-for-healthcare-costs

updating global styles

---

blocks/newslist/newslist.css
blocks/newslist/newslist.js
scripts/scripts.js

Fix #6 
- Added `newslist` block to LCP blocks as this will be the main content on home/vertical/category pages
- The container and some text styling wasn't done, will be done after global styles
- Home page looks like this 
- Vertical page looks like this 
Test URLs:
- Before: https://main-newslist--channelco-iot--hlxsites.hlx.live/drafts/ravi/home
- After: https://issue-6-newslist--channelco-iot--hlxsites.hlx.live/drafts/ravi/home

newslist block

---

blocks/resources/resources.css
blocks/resources/resources.js
scripts/scripts.js

Same block to pull in data from index based on urls in the block in two views.
Default - Card view
list style - List view
Fix #11 
Test URLs:
- Before: https://main--channelco-iot--hlxsites.hlx.page/drafts/amol/resources
- After: https://issue-11-resources--channelco-iot--hlxsites.hlx.page/drafts/amol/resources

Issue 11 resources block

---

blocks/calendar/calendar.css
blocks/calendar/calendar.js

Added Event Calendar functionality that is driven by events created in https://main--channelco-iot--hlxsites.hlx.page/event-calendar/events.json 
Fix #16 
Test URLs:
- Before: https://main--channelco-iot--hlxsites.hlx.page/event-calendar/month
- After: https://issue-16-calendar--channelco-iot--hlxsites.hlx.page/event-calendar/month

Issue 16 calendar

---

blocks/aside/aside.css
blocks/newslist/newslist.css
blocks/newslist/newslist.js
scripts/delayed.js
scripts/scripts.js
styles/styles.css

Fix #30, #32 
Test URLs:
- Before: https://main--channelco-iot--hlxsites.hlx.live/drafts/ravi/energy
- After: https://issue-32-fix-styles--channelco-iot--hlxsites.hlx.live/drafts/ravi/energy

fix: styles for newslist, hero, aside

---

scripts/scripts.js
styles/styles.css

Switched to grid template in css
Fix #34 
Test URLs:
- Before: https://main--channelco-iot--hlxsites.hlx.page/verticals/hospitality/cooking-with-iot-in-commercial-kitchens
- After: https://bug-fix-article-key--channelco-iot--hlxsites.hlx.page/verticals/hospitality/cooking-with-iot-in-commercial-kitchens

CSS fix for article key

---

blocks/newslist/newslist.js

Fix #41 
**Note**: The performance drop is due to images causing CLS in home page listing. Will be handled in https://github.com/hlxsites/channelco-iot/issues/40
Test URLs:
- Before: https://main--channelco-iot--hlxsites.hlx.live/drafts/ravi/home
- After: https://issue-41-search-internalpaths--channelco-iot--hlxsites.hlx.live/drafts/ravi/home

fix: skip internal paths from the query index

---

scripts/scripts.js
styles/styles.css

Fix #<gh-issue-id>
Test URLs:
- Before: https://main--channelco-iot--hlxsites.hlx.page/drafts/cole/get-the-iotsi-ebook-seeing-is-believing-with-computer-vision
- After: https://issue-8-article-content--channelco-iot--hlxsites.hlx.page/drafts/cole/get-the-iotsi-ebook-seeing-is-believing-with-computer-vision

Issue 8 article content

---

blocks/newslist/newslist.js
scripts/scripts.js

- Added ability to pull in value dynamically from URL Params (needed for author and tag pages)
- Remove block if misconfigured
- Switched to using block config instead to make authoring easier
Fix #27 
Test URLs:
- Before: https://main--channelco-iot--hlxsites.hlx.page/drafts/amol/newslist
- After: https://issue-27-dynamic-filters--channelco-iot--hlxsites.hlx.page/drafts/amol/newslist
- After: https://issue-27-dynamic-filters--channelco-iot--hlxsites.hlx.page/drafts/amol/newslist?id=Point%20of%20sale
- After: https://issue-27-dynamic-filters--channelco-iot--hlxsites.hlx.page/drafts/amol/newslist?id=Point%20of%20sale&q=iot

Issue 27 dynamic filters

---

blocks/aside/aside.js
scripts/delayed.js
styles/styles.css

Fix #28 
Test URLs:
- After: https://issue-28-ads--channelco-iot--hlxsites.hlx.page/verticals/hospitality/cooking-with-iot-in-commercial-kitchens

Issue 28 ads

---

blocks/newslist/newslist.css
blocks/newslist/newslist.js

Fix #40 
Test URLs:
- After: https://issue-40-newslist-cls--channelco-iot--hlxsites.hlx.live/

fix: newslist CLS

---

blocks/header/header.js

Fix #<[31](https://github.com/hlxsites/channelco-iot/issues/31)>
Test URLs:
- After: [https://<branch>--channelco-iot--hlxsites.hlx.page/](https://issue-31-search-bar-bug-fix--channelco-iot--hlxsites.hlx.page/)

Issue 31 search bar bug fix

---

fstab.yaml

Fix #54 
Test URLs:
- After: https://folder-mapping--channelco-iot--hlxsites.hlx.page/

feat: using folder mapping for category pages

---

blocks/header/header.js

Fix #57 
Test URLs:
- After: https://issue-57-tempfix-nav-links--channelco-iot--hlxsites.hlx.live/

fix: temp fix for nav links until CDN rewrites are in place

---

blocks/header/header.css

Fix #60 
Test URLs:
- After: https://issue-60-header-alignment--channelco-iot--hlxsites.hlx.live/

fix: header alignment issues

---

blocks/header/header.css

Fix #60 
Test URLs:
- Before: https://main--channelco-iot--hlxsites.hlx.live/
- After: https://issue-60-header-alignment_1--channelco-iot--hlxsites.hlx.live/

fix: mobile nav misalignment

---

blocks/aside/aside.css
blocks/aside/aside.js
blocks/video/video.css
blocks/video/video.js
styles/styles.css

Fix #67 
Fixed the CLS and TBT of video block by using the IntersectionObserver and changing the aside css to avoid the CLS
Test URLs:
- Before: https://main--channelco-iot--hlxsites.hlx.page/content/kmc-brings-building-automation-systems-under-control
- After: https://issue-67-intersection-observer--channelco-iot--hlxsites.hlx.live/content/kmc-brings-building-automation-systems-under-control

fix: Video block improvements

---

blocks/header/header.js
blocks/hero/hero.js
blocks/newslist/newslist.js
styles/styles.css

Fix #66 
There're still 2 issues.
To fix these, we may need to request the customer to provide us the high resolution image with the display aspect ratio.
Test URLs:
- After: https://issue-66-lhsimprovements--channelco-iot--hlxsites.hlx.page/

fix: LHS Improvements

---

tools/sidekick/config.json

Adding sidekick config to the code
Fix #48 
Test URLs:
- After: https://sidekick-config--channelco-iot--hlxsites.hlx.page/

Adding sidekick config
